config/routes.rb
Rails.application.routes.draw do
	# routes
	# HTTP verbs: get, post, put, patch, delete
	# verb 'url/path'
   #get 'students/index'


  # SHOW Routes
  get 'students'	=> 'students#index' #Student index (Show All Students)
  get 'students/:id' => 'students#show', as: 'student', id: /\d+/ #Student Show (Show a Student)


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Create routes
  get 'students/new' => 'students#new', as: 'new_student'
  post 'students' => 'students#create'

  #Update routes
  get 'students/:id/edit' => 'students#edit', as: 'edit_student', id:/\d+/
  patch 'students/:id' => 'students#update'

  #Delete route
  delete 'students/:id' => 'students#destroy' #, as: 'destroy_student', id:/\d+/

    root to: 'students#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
	validates :name, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
  	@students = Student.order(:name) #Load all students ordered by name
  end
  #Automatically load the app/view/students/index.html.erb	

  def show
  	@student = find_student
  end
   #Automatically load the app/view/students/show.html.erb

   def new
   	@student = Student.new
   end
   # Automatically load the app/view/students/new.html.erb

   def create
   	@student = Student.new(student_params)

   	if @student.save #if the validations pass
   		redirect_to @student
   	else #if the validation fails
   		render :new #Render the view associated with the new action
   	end
   end
   #This action does not have an associate view

   def edit
    @student = find_student
   end
   #automatically loads the associated view app/views/students/edit.html.erb

   def update
    @student = find_student

    if @student.update(student_params) #if validation pass
      redirect_to @student #Redirect to the show action for this student
    else
      render :edit #render the edit view to show the form again and display validaiton
    end
   end
   #No view associated with this action we either redirrect or render

   def destroy
    @student = find_student
    @student.destroy

    redirect_to students_url #redirects to the students index page.
   end

   private

    def student_params
      params.require(:student).permit(:name)
    end

    def find_student
      @student = Student.find(params[:id]) #Load students mentioned by id in the route
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WithoutMagic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render partial: 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <h1>Student Records Application</h1>
</header>

app/views/students/_form.html.erb
<!-- A form will go here -->
<%= form_for(@student) do |f| %>
<% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
	<%= f.label :name %>
</div>
<div>
	<%= f.text_field :name %>
</div>
	<%= f.submit %>

<% end %>

app/views/students/_student.html.erb
<!-- 

	The name of the partial should match the model, with a prepended underscore.
	The name of the variable we use within the partial should match the partial name
 -->

<div class = 'student'>
		<p>
		
			<strong>Name:</strong> <%= link_to student.name, student_path(student)%>
			- <%= link_to 'edit',edit_student_path(student) %>
			- <%= link_to 'delete', student_path(student), method: :delete, data: {confirm: "Are you sure you want to delete this student?"} %>
		</p>
	</div>

app/views/students/edit.html.erb
<h2>Edit Student</h2>

<%= render partial: 'form' %>

app/views/students/index.html.erb
<h2>All Students</h2>
	
	<%= render partial: 'student', collection: @students %>

	<!-- This is the shorter form for above if you have followed the proper naming conventions--><%= render @students %>


<p>
	<%= link_to 'Create New Student', new_student_path %>
</p>

app/views/students/new.html.erb
<h2>Create a new Student</h2> 

<!-- A form will go here -->
<%= form_for(@student) do |f| %>
<% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
	<%= f.label :name %>
</div>
<div>
	<%= f.text_field :name %>
</div>
	<%= f.submit %>

<% end %>

app/views/students/show.html.erb
<h2>Student Information</h2>

	<%= render partial: 'student', object: @student %>

	<p><%= link_to 'Back to All Students', students_path %></p>
	<!--<p><a href="/students">Back to Students</a></p>-->